Update files to latest

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,6 +3,10 @@ install_packages openjfx adb android-tools-fastboot openjdk-11-jdk || exit 1
 
 git_clone https://github.com/francescotescari/XiaoMiToolV2 -b linux || exit 1
 cd XiaoMiToolV2
+for i in {adb,fastboot}; do
+echo "Copying ${i}..."
+cp `which $i` ./res/tools/${i} || error "Failed to copy ${i}!"
+done
 echo "Building XiaoMi Tool..."
 case "$arch" in
     "32") JAVA_HOME=/usr/lib/jvm/java-11-openjdk-armhf ./gradlew build || error "Failed to build XiaoMiToolV2!" ;;
@@ -13,14 +17,14 @@ echo "Creating menu shortcut..."
 echo "[Desktop Entry]
 Name=XiaoMi Tool
 Comment=XiaoMiTool is the all-in-one tool to make modding easy for everyone with a Xiaomi smartphone.
-Exec=gksudo -k -u root JAVA_HOME=$JAVA_HOME $HOME/XiaoMiToolV2/gradlew run
+Exec=JAVA_HOME=$JAVA_HOME $HOME/XiaoMiToolV2/gradlew run
 Icon=$(dirname "$0")/icon-64.png
 Terminal=false
 Type=Application
-Categories=System" > ~/.local/share/applications/XiaoMiTool.desktop || error "Failed to create menu shortcut."
+Categories=Utilities;" > ~/.local/share/applications/XiaoMiTool.desktop || error "Failed to create menu shortcut."
 
 echo "Creating execution script..."
-echo "#!/bin/sh
-$HOME/XiaoMiToolV2/gradlew run " | sudo tee /usr/local/bin/xiaomitool >/dev/null
+echo "#!/bin/bash
+JAVA_HOME=$JAVA_HOME $HOME/XiaoMiToolV2/gradlew run " | sudo tee /usr/local/bin/xiaomitool >/dev/null
 sudo chmod +x /usr/local/bin/xiaomitool || error "Failed to make execution script executable."
 
